"""Non-executing resource declarations for complete serial workload inventories.

Separate from short development budgets. Consistency does not confer resource
availability, numerical acceptance, process enforcement or run authorization.
All generated archive and scratch allocations are retained in the disk total.
"""
from dataclasses import asdict, dataclass, fields

from .execution_workload import summarize_workload


@dataclass(frozen=True)
class TaskEnvelope:
    task_id: str
    max_wall_seconds: int
    non_solver_seconds: int
    max_job_commit_bytes: int
    archive_bytes: int
    scratch_bytes: int
    max_threads: int
    max_variables: int
    max_constraints: int


@dataclass(frozen=True)
class SerialResourceBudget:
    max_total_wall_seconds: int
    controller_seconds: int
    supervisor_additional_commit_bytes: int
    commit_reserve_bytes: int
    max_additional_commit_bytes: int
    disk_reserve_bytes: int
    max_additional_disk_bytes: int
    max_threads: int


def _validate_positive_fields(item, skip=()):
    for field in fields(item):
        if field.name in skip:
            continue
        value = getattr(item, field.name)
        if type(value) is not int or value <= 0:
            raise ValueError('explicit positive integer resource required: '+field.name)


def check_resource_contract(normals, episodes, envelopes, budget):
    """Check a proposed serial reservation without changing any runtime cap.

    non_solver_seconds must cover preparation, model creation, loading, audits,
    archiving, replay, shutdown and solver/interface overrun for the whole task.
    It is a supplied allowance, not an observed or proven sufficient duration.
    Archive/scratch cover all generated bytes and are summed without reclamation.
    The host/directory bindings and hard supervisor remain separate requirements.
    """
    workload = summarize_workload(normals, episodes)
    if type(budget) is not SerialResourceBudget:
        raise ValueError('typed serial resource budget required')
    _validate_positive_fields(budget)
    if (type(envelopes) is not tuple
            or any(type(item) is not TaskEnvelope for item in envelopes)):
        raise ValueError('explicit typed task envelope inventory required')
    for item in envelopes:
        if type(item.task_id) is not str or not item.task_id.strip():
            raise ValueError('explicit task envelope ID required')
        _validate_positive_fields(item, ('task_id',))
    by_id = {item.task_id: item for item in envelopes}
    if (len(by_id) != len(envelopes)
            or set(by_id) != {row['task_id'] for row in workload['rows']}):
        raise ValueError('exactly one envelope per declared task required')
    errors, rows = [], []
    for row in workload['rows']:
        envelope = by_id[row['task_id']]
        required_wall = row['reserved_solver_seconds']+envelope.non_solver_seconds
        if envelope.max_wall_seconds < required_wall:
            errors.append((envelope.task_id, 'task_wall_reservation_shortfall'))
        if envelope.max_threads > budget.max_threads:
            errors.append((envelope.task_id, 'thread_cap_exceeds_plan'))
        rows.append(dict(task_id=envelope.task_id, solver_calls=row['solver_calls'],
                         required_declared_wall_seconds=required_wall))
    wall = sum(item.max_wall_seconds for item in envelopes)+budget.controller_seconds
    commit = (max(item.max_job_commit_bytes for item in envelopes)
              +budget.supervisor_additional_commit_bytes+budget.commit_reserve_bytes)
    disk = sum(item.archive_bytes+item.scratch_bytes for item in envelopes)+budget.disk_reserve_bytes
    for observed, cap, error in (
        (wall, budget.max_total_wall_seconds, 'total_wall_reservation_shortfall'),
        (commit, budget.max_additional_commit_bytes, 'commit_reservation_shortfall'),
        (disk, budget.max_additional_disk_bytes, 'disk_reservation_shortfall'),
    ):
        if observed > cap:
            errors.append(('serial_plan', error))
    return dict(schema='rq2_serial_execution_resource_contract_v1', workload=workload,
                envelopes=tuple(asdict(item) for item in envelopes), budget=asdict(budget),
                tasks=tuple(rows), reserved_total_wall_seconds=wall,
                required_additional_commit_bytes=commit, required_additional_disk_bytes=disk,
                errors=tuple(errors), declaration_consistent=not errors,
                assumptions=('one_quiescent_job_at_a_time', 'no_scratch_reclamation', 'no_retries'),
                unresolved=workload['unresolved']+(
                    'envelope_measurements', 'host_and_volume_binding',
                    'hard_process_enforcement', 'real_scale_executor_integration'),
                whole_task_resources_verified=False, execution_authorized=False, formal_ready=False)
