"""Frozen scenario definitions for stochastic planning baselines."""

from .common_input_signature import (
    COMMON_INPUT_SIGNATURE_SCHEMA,
    build_common_input_signature,
    common_input_signature_sha256,
    normalize_common_input_signature,
)
from .frozen_tree import (
    DemandState,
    FrozenScenarioTree,
    PlanningPolicy,
    ProjectState,
    ProjectTiming,
    QuarterDecisionGroups,
    ScenarioLeaf,
    ScenarioNode,
    load_frozen_scenario_tree,
    parse_frozen_scenario_tree,
)
from .rts_gmlc_cfe_deficit import (
    CFE_DEFICIT_FORMULA,
    CFE_DEFICIT_PARAMETER_STATUS,
    RENEWABLE_UNIT_TYPES,
    CfeOperatingLimit,
    RtsGmlcCfeDeficitPoint,
    RtsGmlcCfeDeficitProfile,
    derive_cfe_operating_limit,
    derive_rts_gmlc_cfe_deficit,
    load_rts_gmlc_cfe_deficit_profile,
)
from .scenario_reduction import (
    SCENARIO_REDUCTION_PARAMETER_STATUS,
    ScenarioReductionResult,
    reduce_scenarios_fast_forward,
)
from .temporal_scenario_reduction import (
    TEMPORAL_SCENARIO_REDUCTION_PARAMETER_STATUS,
    TemporalScenarioReductionResult,
    reduce_temporal_scenarios_fast_forward,
)
from .temporal_trace_scenario_generator import (
    TEMPORAL_TRACE_PARAMETER_STATUS,
    GeneratedTemporalScenarioSet,
    TemporalNetworkScenario,
    TemporalTraceScenarioConfig,
    generate_temporal_holdout_scenarios,
)
from .trace_scenario_generator import (
    TRACE_SCENARIO_PARAMETER_STATUS,
    GeneratedScenarioSet,
    TraceScenarioConfig,
    TraceShape,
    generate_holdout_scenarios,
    load_peak_normalized_shape_from_csv,
    load_trace_shape_from_csv,
)

__all__ = [
    "CFE_DEFICIT_FORMULA",
    "CFE_DEFICIT_PARAMETER_STATUS",
    "COMMON_INPUT_SIGNATURE_SCHEMA",
    "RENEWABLE_UNIT_TYPES",
    "SCENARIO_REDUCTION_PARAMETER_STATUS",
    "TEMPORAL_SCENARIO_REDUCTION_PARAMETER_STATUS",
    "TEMPORAL_TRACE_PARAMETER_STATUS",
    "TRACE_SCENARIO_PARAMETER_STATUS",
    "CfeOperatingLimit",
    "DemandState",
    "FrozenScenarioTree",
    "GeneratedScenarioSet",
    "GeneratedTemporalScenarioSet",
    "PlanningPolicy",
    "ProjectState",
    "ProjectTiming",
    "QuarterDecisionGroups",
    "RtsGmlcCfeDeficitPoint",
    "RtsGmlcCfeDeficitProfile",
    "ScenarioLeaf",
    "ScenarioNode",
    "ScenarioReductionResult",
    "TemporalNetworkScenario",
    "TemporalScenarioReductionResult",
    "TemporalTraceScenarioConfig",
    "TraceScenarioConfig",
    "TraceShape",
    "build_common_input_signature",
    "common_input_signature_sha256",
    "derive_cfe_operating_limit",
    "derive_rts_gmlc_cfe_deficit",
    "generate_holdout_scenarios",
    "generate_temporal_holdout_scenarios",
    "load_frozen_scenario_tree",
    "load_peak_normalized_shape_from_csv",
    "load_rts_gmlc_cfe_deficit_profile",
    "load_trace_shape_from_csv",
    "normalize_common_input_signature",
    "parse_frozen_scenario_tree",
    "reduce_scenarios_fast_forward",
    "reduce_temporal_scenarios_fast_forward",
]
